---
monitoring_directory: /opt/devops-lab/monitoring
zabbix_web_port: 8080
grafana_port: 3000
zabbix_server_port: 10051
zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_password: "{{ lookup('env', 'ZABBIX_DB_PASSWORD') }}"
